/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/eIHqdtThWyA
 */
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"

export function chatbot() {
  return (
    <div className="w-full h-screen border border-gray-200 grid flex-1 rounded-lg shadow dark:border-gray-800">
      <div className="grid border-t items-center p-4">
        <div className="flex items-center space-x-4">
          <img
            alt="Logo"
            className="rounded-full"
            height="32"
            src="/placeholder.svg"
            style={{
              aspectRatio: "32/32",
              objectFit: "cover",
            }}
            width="32"
          />
          <div className="grid">
            <p className="text-sm font-semibold">ChatGPT</p>
            <p className="text-xs text-gray-500 dark:text-gray-400">Online</p>
          </div>
        </div>
        <Button size="sm">New Chat</Button>
      </div>
      <div className="border-t p-4 flex-1 overflow-auto grid gap-4">
        <div className="flex flex-col items-end space-y-2">
          <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
            <p className="text-sm">Hi there! 👋 How can I assist you today?</p>
          </div>
          <p className="text-xs text-gray-500">2:35 PM</p>
        </div>
        <div className="flex flex-col items-start space-y-2">
          <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
            <p className="text-sm">I need help with setting up my email. Can you guide me through it?</p>
          </div>
          <p className="text-xs text-gray-500">2:36 PM</p>
        </div>
        <div className="flex flex-col items-end space-y-2">
          <div className="rounded-lg bg-gray-100 p-4 dark:bg-gray-800">
            <p className="text-sm">Sure! I can help you with that. Let's get started.</p>
          </div>
          <p className="text-xs text-gray-500">2:37 PM</p>
        </div>
      </div>
      <div className="border-t grid items-center p-4">
        <Input className="rounded-full border-0" id="message" placeholder="Type your message here..." />
        <Button className="rounded-full p-2" variant="ghost">
          <SendIcon className="w-4 h-4" />
          <span className="sr-only">Send</span>
        </Button>
      </div>
    </div>
  )
}


function SendIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m22 2-7 20-4-9-9-4Z" />
      <path d="M22 2 11 13" />
    </svg>
  )
}
